#!/usr/bin/env bash
# Interactive .env generator for chubi-pocket-be VPS deploys.
# Run on the VPS after uploading the code. See DEPLOY.md section 4.
#
# Usage:
#   ./scripts/setup-vps.sh dev          # dev environment (DuckDNS, APP_ENV=development)
#   ./scripts/setup-vps.sh prod         # prod environment (real domain, APP_ENV=production)
#   ./scripts/setup-vps.sh dev --force  # overwrite existing .env

set -euo pipefail

cd "$(dirname "$0")/.."

ENV_KIND="${1:-}"
FORCE=0
if [[ "${2:-}" == "--force" ]]; then
  FORCE=1
fi

if [[ "$ENV_KIND" != "dev" && "$ENV_KIND" != "prod" ]]; then
  echo "Usage: $0 <dev|prod> [--force]"
  exit 1
fi

TEMPLATE=".env.${ENV_KIND}.example"
if [[ ! -f "$TEMPLATE" ]]; then
  echo "Template not found: $TEMPLATE"
  exit 1
fi

if [[ -f .env && $FORCE -eq 0 ]]; then
  echo ".env already exists. Refusing to overwrite."
  echo "Re-run with --force to replace it (existing secrets will be lost)."
  exit 1
fi

echo "==> chubi-pocket-be $ENV_KIND setup"
echo "    Press Enter on a secret prompt to auto-generate."
echo

# --- DOMAIN ---
if [[ "$ENV_KIND" == "dev" ]]; then
  DOMAIN_HINT="e.g. chubipocket-dev.duckdns.org"
else
  DOMAIN_HINT="e.g. api.chubipocket.com"
fi
read -rp "DOMAIN ($DOMAIN_HINT): " DOMAIN
if [[ -z "$DOMAIN" ]]; then
  echo "DOMAIN is required."
  exit 1
fi

# --- DB_USER (default chubadmin) ---
read -rp "DB_USER [chubadmin]: " DB_USER
DB_USER="${DB_USER:-chubadmin}"

# --- DB_NAME (default chubi_pocket_db) ---
read -rp "DB_NAME [chubi_pocket_db]: " DB_NAME
DB_NAME="${DB_NAME:-chubi_pocket_db}"

# --- DB_PASSWORD (silent, autogen on empty) ---
read -rsp "DB_PASSWORD (Enter to generate): " DB_PASSWORD
echo
DB_PASSWORD_GENERATED=0
if [[ -z "$DB_PASSWORD" ]]; then
  DB_PASSWORD="$(openssl rand -base64 24)"
  DB_PASSWORD_GENERATED=1
fi

# --- JWT_SECRET (silent, autogen on empty) ---
read -rsp "JWT_SECRET (Enter to generate): " JWT_SECRET
echo
JWT_SECRET_GENERATED=0
if [[ -z "$JWT_SECRET" ]]; then
  JWT_SECRET="$(openssl rand -hex 32)"
  JWT_SECRET_GENERATED=1
fi

# APP_ENV defaults — dev uses development for verbose logs, prod uses production.
if [[ "$ENV_KIND" == "dev" ]]; then
  APP_ENV="development"
else
  APP_ENV="production"
fi

# --- Write .env (umask so the file is created 600 from the start) ---
umask 077
cat > .env <<EOF
# Generated by scripts/setup-vps.sh ($ENV_KIND) on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
DOMAIN=$DOMAIN

APP_ENV=$APP_ENV

DB_USER=$DB_USER
DB_PASSWORD=$DB_PASSWORD
DB_NAME=$DB_NAME

JWT_SECRET=$JWT_SECRET
JWT_EXPIRATION_HOURS=720
EOF
chmod 600 .env

# --- Summary ---
mask() { printf '%s' "$1" | sed -E 's/^(.{4}).*(.{2})$/\1…\2/'; }

echo
echo "==> .env written ($(wc -c < .env) bytes, chmod 600)"
echo "    DOMAIN       = $DOMAIN"
echo "    APP_ENV      = $APP_ENV"
echo "    DB_USER      = $DB_USER"
echo "    DB_NAME      = $DB_NAME"
echo "    DB_PASSWORD  = $(mask "$DB_PASSWORD")"
echo "    JWT_SECRET   = $(mask "$JWT_SECRET")"

# Print full generated secrets ONCE so the user can save them in a password manager.
if [[ $DB_PASSWORD_GENERATED -eq 1 || $JWT_SECRET_GENERATED -eq 1 ]]; then
  echo
  echo "==> Save these in your password manager NOW (printed once, never shown again):"
  if [[ $DB_PASSWORD_GENERATED -eq 1 ]]; then
    echo "    DB_PASSWORD = $DB_PASSWORD"
  fi
  if [[ $JWT_SECRET_GENERATED -eq 1 ]]; then
    echo "    JWT_SECRET  = $JWT_SECRET"
  fi
fi

echo
echo "Next: docker compose -f docker-compose.deploy.yml up -d --build"
